project:
  type: website
  output-dir: docs

website:
  title: "Diabetes Prediction"
  navbar:
    left:
      - text: Analysis
        href: Analysis.html
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



