project:
  type: website

website:
  title: "diabetes_prediction_website"
  navbar:
    left:
      - text: Analysis
        href: analysis.html
      

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



